steps:
  - id: 'env'
    name: bash
    args: ['-c', 'echo -e $$ENV > ./.env']
    secretEnv: ['ENV']

  - id: 'npm-env'
    name: bash
    args: ['-c', 'echo -e "\n//npm.pkg.github.com/:_authToken=$$GITHUB_TOKEN" >> .npmrc']
    secretEnv: ['GITHUB_TOKEN']

  - id: 'build'
    name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-t',
        '${_GCP_LOCATION}-docker.pkg.dev/$PROJECT_ID/$_GCP_ARTIFACT_REGISTRY/$_GCP_IMAGE_NAME:$BUILD_ID',
        '--build-arg',
        'BUILD_ID=$BUILD_ID',
        '-f',
        './Dockerfile',
        '.',
      ]
    env:
      - 'DOCKER_BUILDKIT=1'

  - id: 'push'
    name: gcr.io/cloud-builders/docker
    args:
      [
        'push',
        '${_GCP_LOCATION}-docker.pkg.dev/$PROJECT_ID/$_GCP_ARTIFACT_REGISTRY/$_GCP_IMAGE_NAME:$BUILD_ID',
      ]

  - id: 'deploy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '$_GCP_SERVICE_NAME',
        '--image',
        '${_GCP_LOCATION}-docker.pkg.dev/$PROJECT_ID/$_GCP_ARTIFACT_REGISTRY/$_GCP_IMAGE_NAME:$BUILD_ID',
        '--region',
        '$_GCP_LOCATION',
      ]

images:
  - '${_GCP_LOCATION}-docker.pkg.dev/$PROJECT_ID/$_GCP_ARTIFACT_REGISTRY/$_GCP_IMAGE_NAME:$BUILD_ID'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/jeju-env/versions/latest
      env: 'ENV'
    - versionName: projects/$PROJECT_ID/secrets/github-token/versions/latest
      env: 'GITHUB_TOKEN'
