name: Unit Test

on:
  pull_request:
    branches: [main]

  workflow_dispatch:
    branches: [main, develop]
    inputs:
      name:
        description: 'Who'
        required: true

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      # - name: Set Environment Variables
      #   runs:

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: TestStart
        run: yarn test-ci
